### ISSUE TITLE
Discussion: Pod annotations vs. OMS Agent server config for App metric gathering

### ISSUE THREAD

**Issue by jomalsan** [retaildevcrews/ngsa#654]
There are two ways to have OMS Agent (prometheus as well) gather application metrics from pods in the cluster: Pod annotations, and listing the servers to collect in the OMS Agent config.

We should provide guidance on the pros and cons of using each method and when someone should pick one vs. the other.

Early thoughts:
* @bartr mention that listing the servers provides cleaner data and removes unnecessary tags
* What does the process for adding a new workload to get monitored look like?
* How does each proposed solution scale? For 10 apps, 100 apps, 1000 apps

**Comment by bartr** [comment]
Here's how we do it in the Prometheus config map

```
    scrape_configs:

      - job_name: 'ngsa-memory'
        static_configs:
          - targets: [ 'ngsa-memory.default.svc.cluster.local:8080' ]

      - job_name: 'ngsa-cosmos'
        static_configs:
          - targets: [ 'ngsa-cosmos.default.svc.cluster.local:8080' ]

      - job_name: 'loderunner'
        static_configs:
          - targets: [ 'loderunner.default.svc.cluster.local:8080' ]
```
